// Utility for generating WhatsApp receipt share links & PDF export triggers

export function generateWhatsAppLink(donation, committeeInfo) {
  const phone = donation.mobile ? donation.mobile.replace(/\D/g, '') : '';
  const formattedPhone = phone.length === 10 ? `91${phone}` : phone;

  const amountStr = parseFloat(donation.amount).toLocaleString('en-IN');
  const dateStr = donation.date || new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const paymentStatus = donation.paymentMethod === 'Cash' ? 'CASH RECEIVED ✓' : 'SUCCESSFUL ✓';
  const receiptNo = donation.receiptNo || 'SRS-2026-000001';

  // REQUIREMENT 8 & 9: Permanent clean URL safe for WhatsApp sharing
  const receiptUrl = `https://sree-ram-sena-app.vercel.app/receipt/${encodeURIComponent(receiptNo)}`;

  const text = `🙏 *శ్రీ గణేష్ ప్రీతి*
వినాయక చవితి 2026 సేవా కార్యక్రమానికి మీ విలువైన విరాళానికి హృదయపూర్వక ధన్యవాదములు.

మీ అందించిన సహాయంతో మా సేవా కార్యక్రమాలు మరింత ముందుకు సాగుతాయి.

గణపతి బప్పా మీ కుటుంబానికి ఆరోగ్యం, ఆనందం, ఐశ్వర్యం అందించాలని మనస్పూర్తిగా కోరుకుంటున్నాము. 🙏

🙏 *SREE RAM SENA*
Thank you very much for your generous donation to support Vinayaka Chaturthi 2026.

Your contribution helps us in conducting the festival and seva activities.

May Lord Ganesha bless you and your family with Health, Happiness, Prosperity and Success. 🙏

*RECEIPT NO:* ${receiptNo}
*Amount:* ₹ ${amountStr}/-
*Payment Status:* ${paymentStatus}
*Date:* ${dateStr}

📄 *View & Download Official PDF Receipt:*
${receiptUrl}

*Committee:* ${committeeInfo?.name || 'SREE RAM SENA'}
*Phone:* ${committeeInfo?.phone || '8688496208'}
*UPI ID:* ${committeeInfo?.upiId || 'karthikeyanetha@slc'}
*Instagram:* ${committeeInfo?.instagram || '@sreeramsena_g.p'}

Generated by SREE RAM SENA Divine Manager 🌺`;

  if (formattedPhone) {
    return `https://wa.me/${formattedPhone}?text=${encodedText}`;
  }
  return `https://wa.me/?text=${encodedText}`;
}

export function amountInWords(num) {
  const n = parseInt(num, 10);
  if (isNaN(n) || n <= 0) return "Zero Rupees Only";

  const a = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  function inWords(number) {
    if (number < 20) return a[number];
    if (number < 100) return b[Math.floor(number / 10)] + (number % 10 !== 0 ? ' ' + a[number % 10] : '');
    if (number < 1000) return a[Math.floor(number / 100)] + ' Hundred' + (number % 100 !== 0 ? ' ' + inWords(number % 100) : '');
    if (number < 100000) return inWords(Math.floor(number / 1000)) + ' Thousand' + (number % 1000 !== 0 ? ' ' + inWords(number % 1000) : '');
    if (number < 10000000) return inWords(Math.floor(number / 100000)) + ' Lakh' + (number % 100000 !== 0 ? ' ' + inWords(number % 100000) : '');
    return inWords(Math.floor(number / 10000000)) + ' Crore' + (number % 10000000 !== 0 ? ' ' + inWords(number % 10000000) : '');
  }

  return `${inWords(n)} Rupees Only`;
}
