export function formatWhatsAppDonationMessage(donation = {}, committeeInfo = {}) {
  const donorRawName = donation.donorName || donation['Donor Name'] || donation.name;
  let salutationName = "Donor";
  if (donorRawName && String(donorRawName).trim() && String(donorRawName).trim().toLowerCase() !== "anonymous devotee") {
    const clean = String(donorRawName).trim();
    salutationName = clean.endsWith("Garu") || clean.endsWith("garu") ? clean : `${clean} Garu`;
  }

  const receiptNo = donation.receiptNo || donation['Receipt No'] || 'SRS-2026-000001';
  const rawAmt = parseFloat(donation.amount || donation.Amount) || 0;
  const amountStr = rawAmt.toLocaleString('en-IN');
  const dateStr = donation.date || donation.Date || new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });

  let yearVal = '2026';
  if (receiptNo.includes('-')) {
    const parts = receiptNo.split('-');
    if (parts[1] && parts[1].length === 4) yearVal = parts[1];
  } else if (donation.date) {
    const yMatch = donation.date.match(/\d{4}/);
    if (yMatch) yearVal = yMatch[0];
  }

  const rawStatus = (donation.paymentStatus || donation.status || donation.paymentMethod || 'Successful').toLowerCase();
  let mappedStatus = '✅ SUCCESSFUL';
  if (rawStatus.includes('pending')) {
    mappedStatus = '🟡 PENDING';
  } else if (rawStatus.includes('partial')) {
    mappedStatus = '🟠 PARTIAL';
  } else if (rawStatus.includes('cancel') || rawStatus.includes('fail')) {
    mappedStatus = '🔴 CANCELLED';
  }

  const receiptUrl = `https://sree-ram-sena-app.vercel.app/receipt/${encodeURIComponent(receiptNo)}`;
  const phone = committeeInfo?.phone || '8688496208';
  const upiId = committeeInfo?.upiId || 'karthikeyanetha@slc';
  const instagram = committeeInfo?.instagram || '@sreeramsena_g.p';

  return `🙏 *శ్రీ గణేశాయ నమః* 🙏

🌺 *SREE RAM SENA*
*VINAYAKA CHATURTHI ${yearVal}*

Dear *${salutationName}*, 🙏

వినాయక చవితి ${yearVal} సేవా కార్యక్రమానికి మీరు అందించిన
విలువైన విరాళానికి శ్రీ రామ్ సేన తరఫున
హృదయపూర్వక ధన్యవాదములు. 🙏

మీ సహకారం మా సేవా కార్యక్రమాలను మరింత
విజయవంతంగా నిర్వహించడానికి ఎంతో విలువైనది.

గణపతి బప్పా మీకు మరియు మీ కుటుంబ సభ్యులకు
ఆరోగ్యం, ఆనందం, ఐశ్వర్యం మరియు విజయాన్ని
అనుగ్రహించాలని మనస్ఫూర్తిగా కోరుకుంటున్నాము. 🌺🙏

🧾 *OFFICIAL DONATION RECEIPT*

━━━━━━━━━━━━━━━━━━
*Receipt No:* ${receiptNo}
*Amount:* ₹${amountStr}/-
*Payment:* ${mappedStatus}
*Date:* ${dateStr}
━━━━━━━━━━━━━━━━━━

📄 *Official Digital Receipt*

View & Download your verified PDF receipt:
${receiptUrl}

🔐 *Officially generated by*
*SREE RAM SENA Divine Manager*

📞 ${phone}
💳 UPI: ${upiId}
📸 Instagram: ${instagram}

🙏 *Thank you for supporting SREE RAM SENA.*
*Ganapathi Bappa Morya!* 🌺`;
}

export function generateWhatsAppLink(donation, committeeInfo) {
  const phone = donation.mobile ? donation.mobile.replace(/\D/g, '') : '';
  const formattedPhone = phone.length === 10 ? `91${phone}` : phone;

  const messageText = formatWhatsAppDonationMessage(donation, committeeInfo);
  const encodedText = encodeURIComponent(messageText);

  if (formattedPhone) {
    return `https://wa.me/${formattedPhone}?text=${encodedText}`;
  }
  return `https://wa.me/?text=${encodedText}`;
}

export function amountInWords(num) {
  const n = parseInt(num, 10);
  if (isNaN(n) || n <= 0) return "Zero Rupees Only";

  const a = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  function inWords(number) {
    if (number < 20) return a[number];
    if (number < 100) return b[Math.floor(number / 10)] + (number % 10 !== 0 ? ' ' + a[number % 10] : '');
    if (number < 1000) return a[Math.floor(number / 100)] + ' Hundred' + (number % 100 !== 0 ? ' ' + inWords(number % 100) : '');
    if (number < 100000) return inWords(Math.floor(number / 1000)) + ' Thousand' + (number % 1000 !== 0 ? ' ' + inWords(number % 1000) : '');
    if (number < 10000000) return inWords(Math.floor(number / 100000)) + ' Lakh' + (number % 100000 !== 0 ? ' ' + inWords(number % 100000) : '');
    return inWords(Math.floor(number / 10000000)) + ' Crore' + (number % 10000000 !== 0 ? ' ' + inWords(number % 10000000) : '');
  }

  return `${inWords(n)} Rupees Only`;
}
