// Live Hybrid Meta WhatsApp Cloud API (v25.0) & 1-Click Auto Dispatch Service for SREE RAM SENA

export const defaultWhatsAppSettings = {
  autoLaunchOnReceipt: true,
  phoneNumberId: "1249745651554312",
  cloudApiToken: "EAAi0IqSBYcIBSDE1xHVdwxlGRJ4pAWIZBWDlr7CqvZBAoUEWuZAzdNEHUzSvhciNYUwdUoSdydbvnD64C2gZAqfcR31L1d950EX2f4mJ368kfihJ0opVHg6ITKVUDam0TF5ESubtCAlckZCWy8lVYbOcHt20gIlIf9vPGRK3m3GOJIdtaxRvq1NYhitfZAQZA3RSoZBRsmJXuHcFJrwPVvxZA62eIgw4CGLdpvWonj016fmzjsiyxkh52ZCQB45YKD63Hg9Ign1XLgpSpAmzlC5qve0wZDZD",
  provider: "meta"
};

export async function sendAutomatedWhatsAppReceipt(donation, committeeInfo, settings = defaultWhatsAppSettings) {
  const phone = donation.mobile ? donation.mobile.replace(/\D/g, '') : '';
  const formattedPhone = phone.length === 10 ? `91${phone}` : phone;

  const amountStr = parseFloat(donation.amount).toLocaleString('en-IN');
  const dateStr = donation.date || new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const paymentStatus = donation.paymentMethod === 'Cash' ? 'CASH RECEIVED ✓' : 'SUCCESSFUL ✓';

  const messageText = `🙏 *శ్రీ గణేష్ ప్రీతి*
వినాయక చవితి 2026 సేవా కార్యక్రమానికి మీ విలువైన విరాళానికి హృదయపూర్వక ధన్యవాదములు.

మీ అందించిన సహాయంతో మా సేవా కార్యక్రమాలు మరింత ముందుకు సాగుతాయి.

గణపతి బప్పా మీ కుటుంబానికి ఆరోగ్యం, ఆనందం, ఐశ్వర్యం అందించాలని మనస్పూర్తిగా కోరుకుంటున్నాము. 🙏

🙏 *SREE RAM SENA*
Thank you very much for your generous donation to support Vinayaka Chaturthi 2026.

Your contribution helps us in conducting the festival and seva activities.

May Lord Ganesha bless you and your family with Health, Happiness, Prosperity and Success. 🙏

*RECEIPT NO:* ${donation.receiptNo}
*Amount:* ₹ ${amountStr}/-
*Payment Status:* ${paymentStatus}
*Date:* ${dateStr}

*Committee:* ${committeeInfo.name}
*Phone:* ${committeeInfo.phone || '8688496208'}
*UPI ID:* ${committeeInfo.upiId || 'sreeramsena@upi'}
*Instagram:* @sreeram.sena

Generated by SREE RAM SENA Divine Manager 🌺`;

  const activeToken = settings.cloudApiToken || defaultWhatsAppSettings.cloudApiToken;
  const activePhoneId = settings.phoneNumberId || defaultWhatsAppSettings.phoneNumberId;

  const encodedText = encodeURIComponent(messageText);
  const waUrl = formattedPhone ? `https://wa.me/${formattedPhone}?text=${encodedText}` : `https://wa.me/?text=${encodedText}`;

  // 1. Try Meta Cloud API v25.0 background dispatch
  if (activeToken && activePhoneId && formattedPhone) {
    try {
      const res = await fetch(`https://graph.facebook.com/v25.0/${activePhoneId}/messages`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${activeToken}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          messaging_product: "whatsapp",
          to: formattedPhone,
          type: "text",
          text: { body: messageText }
        })
      });

      const data = await res.json();
      console.log("Meta Cloud API Live Dispatch Response:", data);

      if (data.messages && data.messages.length > 0) {
        return { success: true, method: "Meta Cloud API Direct", data, url: waUrl };
      }
    } catch (err) {
      console.warn("Meta Cloud API background attempt notice:", err.message);
    }
  }

  // 2. Auto-launch WhatsApp Web / App prefilled tab
  if (settings.autoLaunchOnReceipt) {
    window.open(waUrl, '_blank');
  }

  return { success: true, method: "Auto WhatsApp Tab Launch", url: waUrl };
}
